### ISSUE TITLE
Not able to run project

### ISSUE THREAD

**Issue by naushadqamar** [checkout/checkoutkit-android#1]
There are issue while running project , I am getting error regarding java version.

**Comment by nicolas-maalouf-cko** [comment]
@naushadqamar , what version of the Java SDK are you on?

**Comment by anantshah93** [comment]
Same issue not able to compile project.....

**Comment by anantshah93** [comment]
Finally i found solution

Change this code from checkoutkit 

apply plugin: 'java'
dependencies {
    testCompile 'junit:junit:4.+'
    compile 'com.google.code.gson:gson:2.3.1'
    testCompile 'com.github.tomakehurst:wiremock:1.57'
    sourceCompatibility = 1.7
    targetCompatibility = 1.7
}

**Comment by nicolas-maalouf-cko** [comment]
@anantshah93 
Thank you for sharing your solution;
We updated the plugin to support JDK 8
